---
# Sets up a complete graphical development environment for frontend developing
#

# TODO
# 1. Gnome passwordless login
# 2. rbenv

- hosts: default
  gather_facts: yes

  tasks:
    - include: tasks/nodejs.yml
    - include: tasks/packages.yml
    - include: tasks/users.yml
    - include: tasks/desktop.yml
    - include: tasks/rbenv.yml
