---
# Installs Node.js from the official repository

- name: Import nodesource PGP key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  sudo: yes

- name: Set up nodesource repository
  apt_repository: repo='deb https://deb.nodesource.com/node_5.x vivid main'
  sudo: yes

- name: Install Node.js
  apt: name=nodejs
